os: Visual Studio 2015

platform: x64

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - choco install strawberryperl
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - git clone https://github.com/rakudo/rakudo.git %APPVEYOR_BUILD_FOLDER%\..\rakudo
  - cd %APPVEYOR_BUILD_FOLDER%\..\rakudo
  - perl Configure.pl --gen-moar=HEAD --gen-nqp
  - nmake install
  - SET PATH=%APPVEYOR_BUILD_FOLDER%\..\rakudo\install\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%

build: off

test_script:
  - set NETWORK_TESTING=1
  - prove -v -e "perl6 -Ilib" t/
  - perl6 -Ilib bin/zef --verbose install .
  - SET PATH=%APPVEYOR_BUILD_FOLDER%\..\rakudo\install\share\perl6\site\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - zef --verbose --force install Zef

shallow_clone: true